export const tripList = [
  {
    id: 1,
    code: 1,
    startDate: "02/03/2026",
    endDate: "",
    icon: "/logoBrand.png",
    totalTime: "7:00 AM",
    airline: "Hawaiian Airlines",
    duration: "7:00AM - 4:15PM",
    durationLocation: "HAN (Nhà ga 1) - SGN (Nhà ga 3)",
    stopCount: 1,
    stopDuration: "2h 45m in HNL",
    service: "one way",
    cabin: [
      {
        type: "economy",
        title: "Economy",
        price: 1000000,
        quantity: 5,
      },
      {
        type: "business",
        title: "Business",
        price: 10000000,
        quantity: 5,
      },
    ],
  },
  {
    id: 2,
    code: 2,
    startDate: "02/03/2026",
    endDate: "",
    icon: "/logoBrand.png",
    totalTime: "7h 35m",
    airline: "Japan Airlines",
    duration: "7:00AM - 4:15PM",
    durationLocation: "HAN (Nhà ga 1) - SGN (Nhà ga 3)",
    stopCount: 1,
    stopDuration: "50m in HKG",
    service: "one way",
    cabin: [
      {
        type: "economy",
        title: "Economy",
        price: 1000000,
        quantity: 5,
      },
      {
        type: "business",
        title: "Business",
        price: 10000000,
        quantity: 5,
      },
    ],
  },
  {
    id: 3,
    code: 1,
    startDate: "02/03/2026",
    endDate: "",
    icon: "/logoBrand.png",
    totalTime: "8:20 AM",
    airline: "Hawaiian Airlines",
    duration: "7:00AM - 4:15PM",
    durationLocation: "HAN (Nhà ga 1) - SGN (Nhà ga 3)",
    stopCount: 1,
    stopDuration: "1h 50m in PVG",
    service: "one way",
    cabin: [
      {
        type: "economy",
        title: "Economy",
        price: 1000000,
        quantity: 5,
      },
      {
        type: "business",
        title: "Business",
        price: 10000000,
        quantity: 5,
      },
    ],
  },
  {
    id: 4,
    code: 1,
    startDate: "02/03/2026",
    endDate: "",
    icon: "/logoBrand.png",
    totalTime: "9:47 AM",
    airline: "Delta",
    duration: "7:00AM - 4:15PM",
    durationLocation: "HAN (Nhà ga 1) - SGN (Nhà ga 3)",
    stopCount: 1,
    stopDuration: "4h 05m in ICN",
    service: "one way",
    cabin: [
      {
        type: "economy",
        title: "Economy",
        price: 1000000,
        quantity: 5,
      },
      {
        type: "business",
        title: "Business",
        price: 10000000,
        quantity: 5,
      },
    ],
  },
  {
    id: 5,
    code: 2,
    startDate: "02/03/2026",
    endDate: "",
    icon: "/logoBrand.png",
    totalTime: "11:15 AM",
    airline: "Hawaiian Airlines",
    duration: "7:00AM - 4:15PM",
    durationLocation: "HAN (Nhà ga 1) - SGN (Nhà ga 3)",
    stopCount: 0,
    stopDuration: "Nonstop",
    service: "one way",
    cabin: [
      {
        type: "economy",
        title: "Economy",
        price: 1000000,
        quantity: 5,
      },
      {
        type: "business",
        title: "Business",
        price: 10000000,
        quantity: 5,
      },
    ],
  },
  {
    id: 6,
    code: 1,
    startDate: "02/03/2026",
    endDate: "",
    icon: "/logoBrand.png",
    totalTime: "10:55 AM",
    airline: "Delta",
    duration: "7:00AM - 4:15PM",
    durationLocation: "HAN (Nhà ga 1) - SGN (Nhà ga 3)",
    stopCount: 0,
    stopDuration: "Nonstop",
    service: "one way",
    cabin: [
      {
        type: "economy",
        title: "Economy",
        price: 1000000,
        quantity: 5,
      },
      {
        type: "business",
        title: "Business",
        price: 10000000,
        quantity: 5,
      },
    ],
  },
];
