// app/api/seats/[flightCode]/route.ts
import { LegacySeatMapRecord } from "@/types/seat-type";
import { NextResponse } from "next/server";

// 👉 DATA GHÉP TỪ DATA BẠN ĐÃ GỬI
const seatsData: LegacySeatMapRecord = {
  VN123: {
    flightCode: "VN123",
    seats: [
      {
        id: "business",
        list: [
          // A
          {
            idCabin: "b_a1",
            title: "A1",
            type: "business-flex",
            pos: "left",
            note: "bf",
            buyed: false,
          },
          {
            idCabin: "b_a2",
            title: "A2",
            type: "business-flex",
            pos: "left",
            note: "bf",
            buyed: true,
          },
          {
            idCabin: "b_a3",
            title: "A3",
            type: "business-flex",
            pos: "right",
            note: "bf",
            buyed: false,
          },
          {
            idCabin: "b_a4",
            title: "A4",
            type: "business-flex",
            pos: "right",
            note: "bf",
            buyed: true,
          },

          // B
          {
            idCabin: "b_b1",
            title: "B1",
            type: "business-flex",
            pos: "left",
            note: "bf",
            buyed: false,
          },
          {
            idCabin: "b_b2",
            title: "B2",
            type: "business-flex",
            pos: "left",
            note: "bf",
            buyed: true,
          },
          {
            idCabin: "b_b3",
            title: "B3",
            type: "business-flex",
            pos: "right",
            note: "bf",
            buyed: false,
          },
          {
            idCabin: "b_b4",
            title: "B4",
            type: "business-flex",
            pos: "right",
            note: "bf",
            buyed: true,
          },

          // C
          {
            idCabin: "b_c1",
            title: "C1",
            type: "business-flex",
            pos: "left",
            note: "bf",
            buyed: false,
          },
          {
            idCabin: "b_c2",
            title: "C2",
            type: "business-flex",
            pos: "left",
            note: "bf",
            buyed: true,
          },
          {
            idCabin: "b_c3",
            title: "C3",
            type: "business-flex",
            pos: "right",
            note: "bf",
            buyed: false,
          },
          {
            idCabin: "b_c4",
            title: "C4",
            type: "business-flex",
            pos: "right",
            note: "bf",
            buyed: true,
          },

          // D
          {
            idCabin: "b_d1",
            title: "D1",
            type: "business-smart",
            pos: "left",
            note: "bs",
            buyed: false,
          },
          {
            idCabin: "b_d2",
            title: "D2",
            type: "business-smart",
            pos: "left",
            note: "bs",
            buyed: true,
          },
          {
            idCabin: "b_d3",
            title: "D3",
            type: "business-smart",
            pos: "right",
            note: "bs",
            buyed: false,
          },
          {
            idCabin: "b_d4",
            title: "D4",
            type: "business-smart",
            pos: "right",
            note: "bs",
            buyed: true,
          },

          // E
          {
            idCabin: "b_e1",
            title: "E1",
            type: "business-flex",
            pos: "left",
            note: "bs",
            buyed: false,
          },
          {
            idCabin: "b_e2",
            title: "E2",
            type: "business-flex",
            pos: "left",
            note: "bs",
            buyed: true,
          },
          {
            idCabin: "b_e3",
            title: "E3",
            type: "business-flex",
            pos: "right",
            note: "bs",
            buyed: false,
          },
          {
            idCabin: "b_e4",
            title: "E4",
            type: "business-flex",
            pos: "right",
            note: "bs",
            buyed: true,
          },

          // F
          {
            idCabin: "b_f1",
            title: "F1",
            type: "business-flex",
            pos: "left",
            note: "bs",
            buyed: false,
          },
          {
            idCabin: "b_f2",
            title: "F2",
            type: "business-flex",
            pos: "left",
            note: "bs",
            buyed: true,
          },
          {
            idCabin: "b_f3",
            title: "F3",
            type: "business-flex",
            pos: "right",
            note: "bs",
            buyed: false,
          },
          {
            idCabin: "b_f4",
            title: "F4",
            type: "business-flex",
            pos: "right",
            note: "bs",
            buyed: true,
          },
        ],
      },
      {
        id: "economy",
        list: [
          // A
          {
            idCabin: "e_a1",
            title: "A1",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_a2",
            title: "A2",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_a3",
            title: "A3",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_a4",
            title: "A4",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_a5",
            title: "A5",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_a6",
            title: "A6",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: true,
          },

          // B
          {
            idCabin: "e_b1",
            title: "B1",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_b2",
            title: "B2",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_b3",
            title: "B3",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_b4",
            title: "B4",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_b5",
            title: "B5",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_b6",
            title: "B6",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: false,
          },

          // C
          {
            idCabin: "e_c1",
            title: "C1",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_c2",
            title: "C2",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_c3",
            title: "C3",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_c4",
            title: "C4",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_c5",
            title: "C5",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_c6",
            title: "C6",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: false,
          },

          // D
          {
            idCabin: "e_d1",
            title: "D1",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_d2",
            title: "D2",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_d3",
            title: "D3",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_d4",
            title: "D4",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_d5",
            title: "D5",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_d6",
            title: "D6",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: true,
          },

          // E
          {
            idCabin: "e_e1",
            title: "E1",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_e2",
            title: "E2",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_e3",
            title: "E3",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_e4",
            title: "E4",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_e5",
            title: "E5",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_e6",
            title: "E6",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: false,
          },

          // F
          {
            idCabin: "e_f1",
            title: "F1",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_f2",
            title: "F2",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_f3",
            title: "F3",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_f4",
            title: "F4",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_f5",
            title: "F5",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_f6",
            title: "F6",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: true,
          },

          // G
          {
            idCabin: "e_g1",
            title: "G1",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_g2",
            title: "G2",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_g3",
            title: "G3",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_g4",
            title: "G4",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_g5",
            title: "G5",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_g6",
            title: "G6",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: false,
          },

          // H
          {
            idCabin: "e_h1",
            title: "H1",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_h2",
            title: "H2",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_h3",
            title: "H3",
            type: "economy-flex",
            pos: "left",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_h4",
            title: "H4",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: true,
          },
          {
            idCabin: "e_h5",
            title: "H5",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: false,
          },
          {
            idCabin: "e_h6",
            title: "H6",
            type: "economy-flex",
            pos: "right",
            note: "ef",
            buyed: true,
          },

          // I
          {
            idCabin: "e_i1",
            title: "I1",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_i2",
            title: "I2",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_i3",
            title: "I3",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_i4",
            title: "I4",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_i5",
            title: "I5",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_i6",
            title: "I6",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: false,
          },

          // J
          {
            idCabin: "e_j1",
            title: "J1",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_j2",
            title: "J2",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_j3",
            title: "J3",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_j4",
            title: "J4",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_j5",
            title: "J5",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_j6",
            title: "J6",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: true,
          },

          // K
          {
            idCabin: "e_k1",
            title: "K1",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_k2",
            title: "K2",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_k3",
            title: "K3",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_k4",
            title: "K4",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_k5",
            title: "K5",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_k6",
            title: "K6",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: false,
          },

          // L
          {
            idCabin: "e_l1",
            title: "L1",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_l2",
            title: "L2",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_l3",
            title: "L3",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_l4",
            title: "L4",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_l5",
            title: "L5",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_l6",
            title: "L6",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: true,
          },

          // M
          {
            idCabin: "e_m1",
            title: "M1",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_m2",
            title: "M2",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_m3",
            title: "M3",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_m4",
            title: "M4",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_m5",
            title: "M5",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_m6",
            title: "M6",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: false,
          },

          // N
          {
            idCabin: "e_n1",
            title: "N1",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_n2",
            title: "N2",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_n3",
            title: "N3",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_n4",
            title: "N4",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_n5",
            title: "N5",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_n6",
            title: "N6",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: true,
          },

          // O
          {
            idCabin: "e_o1",
            title: "O1",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_o2",
            title: "O2",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_o3",
            title: "O3",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_o4",
            title: "O4",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_o5",
            title: "O5",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_o6",
            title: "O6",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: false,
          },

          // P
          {
            idCabin: "e_p1",
            title: "P1",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_p2",
            title: "P2",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_p3",
            title: "P3",
            type: "economy-smart",
            pos: "left",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_p4",
            title: "P4",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: true,
          },
          {
            idCabin: "e_p5",
            title: "P5",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: false,
          },
          {
            idCabin: "e_p6",
            title: "P6",
            type: "economy-smart",
            pos: "right",
            note: "es",
            buyed: true,
          },

          // Q
          {
            idCabin: "e_q1",
            title: "Q1",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_q2",
            title: "Q2",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_q3",
            title: "Q3",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_q4",
            title: "Q4",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_q5",
            title: "Q5",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_q6",
            title: "Q6",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: false,
          },

          // R
          {
            idCabin: "e_r1",
            title: "R1",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_r2",
            title: "R2",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_r3",
            title: "R3",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_r4",
            title: "R4",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_r5",
            title: "R5",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_r6",
            title: "R6",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: true,
          },

          // S
          {
            idCabin: "e_s1",
            title: "S1",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_s2",
            title: "S2",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_s3",
            title: "S3",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_s4",
            title: "S4",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_s5",
            title: "S5",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_s6",
            title: "S6",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: false,
          },

          // T
          {
            idCabin: "e_t1",
            title: "T1",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_t2",
            title: "T2",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_t3",
            title: "T3",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_t4",
            title: "T4",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_t5",
            title: "T5",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_t6",
            title: "T6",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: true,
          },

          // U
          {
            idCabin: "e_u1",
            title: "U1",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_u2",
            title: "U2",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_u3",
            title: "U3",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_u4",
            title: "U4",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_u5",
            title: "U5",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_u6",
            title: "U6",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: false,
          },

          // V
          {
            idCabin: "e_v1",
            title: "V1",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_v2",
            title: "V2",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_v3",
            title: "V3",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_v4",
            title: "V4",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_v5",
            title: "V5",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_v6",
            title: "V6",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: true,
          },

          // W
          {
            idCabin: "e_w1",
            title: "W1",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_w2",
            title: "W2",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_w3",
            title: "W3",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_w4",
            title: "W4",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_w5",
            title: "W5",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_w6",
            title: "W6",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: false,
          },

          // X
          {
            idCabin: "e_x1",
            title: "X1",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_x2",
            title: "X2",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_x3",
            title: "X3",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_x4",
            title: "X4",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_x5",
            title: "X5",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_x6",
            title: "X6",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: true,
          },

          // Y
          {
            idCabin: "e_y1",
            title: "Y1",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_y2",
            title: "Y2",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_y3",
            title: "Y3",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_y4",
            title: "Y4",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_y5",
            title: "Y5",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_y6",
            title: "Y6",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: false,
          },

          // Z
          {
            idCabin: "e_z1",
            title: "Z1",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_z2",
            title: "Z2",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_z3",
            title: "Z3",
            type: "economy-server-max",
            pos: "left",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_z4",
            title: "Z4",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: true,
          },
          {
            idCabin: "e_z5",
            title: "Z5",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: false,
          },
          {
            idCabin: "e_z6",
            title: "Z6",
            type: "economy-server-max",
            pos: "right",
            note: "em",
            buyed: true,
          },
        ],
      },
    ],
  },
};
export async function GET(
  req: Request,
  context: { params: Promise<{ flightCode: string }> }
) {
  const { flightCode } = await context.params;

  if (!seatsData[flightCode]) {
    return NextResponse.json(
      {
        status: "error",
        message: `Flight code '${flightCode}' not found`,
      },
      { status: 404 }
    );
  }

  return NextResponse.json({
    status: "success",
    flightCode,
    seats: seatsData[flightCode].seats,
  });
}
